version: "3.8"

networks:
  stack:

services:
  
  compile:
    image: ${REG}webmethods-abe:${TAG}
    environment:
      - projectName=wmsamples-bookstore-api
    volumes:
      - .:/src:rw
    networks:
      - stack