version: 3.9

networks:
  sagnet:

volumes:
  apigw-elasticdata:

services:

  apigateway:
    image: ${REG}webmethods-apigateway-standalone:${TAG_APIGATEWAY}
    ports:
      - "5556:5555"
      - "9072:9072"
    environment: 
      APIGW_ELASTICSEARCH_TENANTID: apigateway
      JAVA_MIN_MEM: 512m
      JAVA_MAX_MEM: 512m
      IDS_HEAP_SIZE: 512m
      JAVA_OPTS: ""
      RUNTIME_WATT_PROPERTIES: "watt.net.timeout=400 watt.server.threadPool=50 watt.server.threadPoolMin=25 watt.net.maxClientKeepaliveConns=10"
    volumes:
      - apigw-elasticdata:/opt/softwareag/InternalDataStore/data:rw
      - ./licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
    hostname: apigateway
    networks:
      - sagnet