version: "3.8"

networks:
  sagnet:

volumes:
  apigw-elasticdata:

services:

  codebuild:
    image: ${REG}webmethods-msr-art-jdbc:${TAG_MSR}
    entrypoint: /opt/softwareag/IntegrationServer/bin/jcode.sh
    command: make BookstoreAPI
    volumes:
      - ./assets/IS/Packages/BookstoreAPI:/opt/softwareag/IntegrationServer/packages/BookstoreAPI:rw
    networks:
      - sagnet

  localdev:
    image: ${REG}webmethods-msr-art-jdbc:${TAG_MSR}
    ports:
      - 5555:5555
    environment: 
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 1g
      JDBC_HOST: postgres
      JDBC_PORT: "5432"
      JDBC_USERNAME: postgres
      JDBC_USERPASSWORD: postgres
    volumes:
      - ./licensing/msr-licenseKey.xml:/opt/softwareag/IntegrationServer/config/licenseKey.xml:rw
      - ./application-localdev.properties:/opt/softwareag/IntegrationServer/application.properties:rw
      - ./workspace/replicate:/opt/softwareag/IntegrationServer/replicate:rw
      - ./libs/postgresql.jar:/opt/softwareag/IntegrationServer/packages/WmJDBCAdapter/code/jars/postgresql.jar:ro
      - ./assets/IS/Packages/BookstoreAPI:/opt/softwareag/IntegrationServer/packages/BookstoreAPI:rw
    networks:
      - sagnet

  apigateway:
    image: ${REG}webmethods-apigateway-standalone:${TAG_APIGATEWAY}
    ports:
      - "5556:5555"
      - "9072:9072"
    environment: 
      APIGW_ELASTICSEARCH_TENANTID: apigateway
      JAVA_MIN_MEM: 512m
      JAVA_MAX_MEM: 512m
      IDS_HEAP_SIZE: 512m
      JAVA_OPTS: ""
      RUNTIME_WATT_PROPERTIES: "watt.net.timeout=400 watt.server.threadPool=50 watt.server.threadPoolMin=25 watt.net.maxClientKeepaliveConns=10"
    volumes:
      - apigw-elasticdata:/opt/softwareag/InternalDataStore/data:rw
      - ./licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
    hostname: apigateway
    networks:
      - sagnet

  # postgress db + load the sql scripts to create tables and fill with some sample records
  postgres:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - ./workspace/postgres-data:/var/lib/postgresql/data
      - ./assets/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./assets/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      - sagnet