<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parseShort</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5n
IGluU3RyaW5nID0gSURhdGFVdGlsLmdldE5vbkVtcHR5U3RyaW5nKHBpcGVsaW5lQ3Vyc29yLCAi
aW5TdHJpbmciKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoKU2hvcnQgb3V0TnVtYmVyID0g
bnVsbDsKaWYobnVsbCAhPSBpblN0cmluZyAmJiAhICIiLmVxdWFscyhpblN0cmluZykpewoJdHJ5
ewoJCW91dE51bWJlciA9IFNob3J0LnBhcnNlU2hvcnQoaW5TdHJpbmcpOwoJfSBjYXRjaChOdW1i
ZXJGb3JtYXRFeGNlcHRpb24gbmZlKXsKCQlvdXROdW1iZXIgPSBudWxsOwoJCXRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKG5mZSk7Cgl9Cn0KCi8vIHJldHVybiBwaXBlbGluZQpJRGF0YUN1cnNv
ciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhVXRpbC5wdXQo
IHBpcGVsaW5lQ3Vyc29yXzEsICJvdXROdW1iZXIiLCBvdXROdW1iZXIgKTsKcGlwZWxpbmVDdXJz
b3JfMS5kZXN0cm95KCk7Cgk=</value>
</Values>
